[package]
name = "rust-lib-reference-genome"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.2.0"
flate2 = "1.0.26"
log = "0.4.17"
rustc-hash = "1.1.0"
simple-error = "0.3.1"
